version: '3'
services:
  redis:
    image: 'registry.cn-hangzhou.aliyuncs.com/hi121/redis:v1'
    restart: always
    volumes:
      - './data/dbs/redis/default:/data'
    networks:
      - lnmp
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlpassword} # 使用环境变量，默认值为mysqlpassword
    volumes:
      - ./data/dbs/mysql:/var/lib/mysql # replace with your mysql data directory
      - ./config/mysql/etc/my.cnf:/etc/mysql/my.cnf
      - ./logs/mysql:/var/log/mysql
    ports:
      - '127.0.0.1:3306:3306'
    networks:
      - lnmp
  ftp:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
    volumes:
      - '/www/docker:/home/username/'
      - '/www/docker/data/ftp/passwd:/etc/pure-ftpd/passwd'
    command: '/run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -P localhost -p 30000:30009 -c 5 -C 5'
    environment:
      FTP_USER_NAME: ${FTP_USER_NAME:-ftpuser}
      FTP_USER_PASS: ${FTP_USER_PASS:-ftppassword}
      FTP_USER_HOME: /home/username
    restart: always
    networks:
      - lnmp
  caddy:
    image: registry.cn-hangzhou.aliyuncs.com/hi121/caddy:v1
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
      - web_data:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - lnmp
  php82:
    image: registry.cn-hangzhou.aliyuncs.com/hi121/php82:v6
    restart: always
    volumes:
      - web_data:/var/www/html
      - ./logs:/var/logs
    networks:
      - lnmp
networks:
  lnmp:
volumes:
  web_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/web
  caddy_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./caddy_config
  caddy_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./caddy_data
