version: '3'
services:
  redis:
    image: 'registry.cn-hangzhou.aliyuncs.com/hi121/redis:v1'
    restart: always
    volumes:
      - './data/dbs/redis/default:/data'
    networks:
      - lnmp
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlpassword} # 使用环境变量，默认值为mysqlpassword
    volumes:
      - ./data/dbs/mysql:/var/lib/mysql # replace with your mysql data directory
      - ./config/mysql/etc/my.cnf:/etc/mysql/my.cnf
      - ./logs/mysql:/var/log/mysql
    ports:
      - '127.0.0.1:3306:3306'
    networks:
      - lnmp

  ftp:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - '/www/docker:/home/username/'
      - '/www/docker/data/ftp/passwd:/etc/pure-ftpd/passwd'
    environment:
      PUBLICHOST: 'localhost'
      FTP_USER_NAME: ${FTP_USER_NAME:-ftpuser}
      FTP_USER_PASS: ${FTP_USER_PASS:-ftppassword}
      FTP_USER_HOME: /home/username
    restart: always
    command: >
      /bin/bash -c "
        mkdir -p /etc/pure-ftpd/passwd &&
        touch /etc/pure-ftpd/passwd/pureftpd.passwd &&
        pure-pw mkdb &&
        /run.sh
      "
  caddy:
    image: registry.cn-hangzhou.aliyuncs.com/hi121/caddy:v1
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
      - web_data:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - lnmp
  php82:
    image: registry.cn-hangzhou.aliyuncs.com/hi121/php82:v6
    restart: always
    user: '100000:231072' # 匹配userns-remap映射的用户ID
    volumes:
      - web_data:/var/www/html
      - ./logs:/var/logs
    networks:
      - lnmp
    command: >
      /bin/sh -c "
        chown -R 100000:231072 /var/www/html &&
        chmod -R 755 /var/www/html &&
        php-fpm
      "
networks:
  lnmp:
volumes:
  web_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/web
  caddy_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./caddy_config
  caddy_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./caddy_data
